# Mapping of Google's top-level domains to their full spelled-out names
tld_names = {
    "ad": "Andorra",
    "ae": "United Arab Emirates",
    "al": "Albania",
    "am": "Armenia",
    "as": "American Samoa",
    "at": "Austria",
    "az": "Azerbaijan",
    "ba": "Bosnia and Herzegovina",
    "be": "Belgium",
    "bf": "Burkina Faso",
    "bg": "Bulgaria",
    "bi": "Burundi",
    "bj": "Benin",
    "bs": "Bahamas",
    "bt": "Bhutan",
    "by": "Belarus",
    "ca": "Canada",
    "cat": "Catalonia",
    "cd": "Democratic Republic of the Congo",
    "cf": "Central African Republic",
    "cg": "Congo",
    "ch": "Switzerland",
    "ci": "Côte d'Ivoire",
    "cl": "Chile",
    "cm": "Cameroon",
    "cn": "China",
    "co.ao": "Angola",
    "co.bw": "Botswana",
    "co.ck": "Cook Islands",
    "co.cr": "Costa Rica",
    "co.id": "Indonesia",
    "co.il": "Israel",
    "co.in": "India",
    "co.jp": "Japan",
    "co.ke": "Kenya",
    "co.kr": "South Korea",
    "co.ls": "Lesotho",
    "co.ma": "Morocco",
    "co.mz": "Mozambique",
    "co.nz": "New Zealand",
    "co.th": "Thailand",
    "co.tz": "Tanzania",
    "co.ug": "Uganda",
    "co.uk": "United Kingdom",
    "co.uz": "Uzbekistan",
    "co.ve": "Venezuela",
    "co.vi": "Virgin Islands",
    "co.za": "South Africa",
    "co.zm": "Zambia",
    "co.zw": "Zimbabwe",
    "com.af": "Afghanistan",
    "com.ag": "Antigua and Barbuda",
    "com.ar": "Argentina",
    "com.au": "Australia",
    "com.bd": "Bangladesh",
    "com.bh": "Bahrain",
    "com.bn": "Brunei",
    "com.bo": "Bolivia",
    "com.br": "Brazil",
    "com.bz": "Belize",
    "com.co": "Colombia",
    "com.cu": "Cuba",
    "com.cy": "Cyprus",
    "com.do": "Dominican Republic",
    "com.ec": "Ecuador",
    "com.eg": "Egypt",
    "com.et": "Ethiopia",
    "com.fj": "Fiji",
    "com.gh": "Ghana",
    "com.gi": "Gibraltar",
    "com.gt": "Guatemala",
    "com.hk": "Hong Kong",
    "com.jm": "Jamaica",
    "com.kh": "Cambodia",
    "com.kw": "Kuwait",
    "com.lb": "Lebanon",
    "com.ly": "Libya",
    "com.mm": "Myanmar",
    "com.mt": "Malta",
    "com.mx": "Mexico",
    "com.my": "Malaysia",
    "com.na": "Namibia",
    "com.ng": "Nigeria",
    "com.ni": "Nicaragua",
    "com.np": "Nepal",
    "com.om": "Oman",
    "com.pa": "Panama",
    "com.pe": "Peru",
    "com.pg": "Papua New Guinea",
    "com.ph": "Philippines",
    "com.pk": "Pakistan",
    "com.pr": "Puerto Rico",
    "com.py": "Paraguay",
    "com.qa": "Qatar",
    "com.sa": "Saudi Arabia",
    "com.sb": "Solomon Islands",
    "com.sg": "Singapore",
    "com.sl": "Sierra Leone",
    "com.sv": "El Salvador",
    "com.tj": "Tajikistan",
    "com.tr": "Turkey",
    "com.tw": "Taiwan",
    "com.ua": "Ukraine",
    "com.uy": "Uruguay",
    "com.vc": "Saint Vincent and the Grenadines",
    "com.vn": "Vietnam",
    "cv": "Cape Verde",
    "cz": "Czech Republic",
    "de": "Germany",
    "dj": "Djibouti",
    "dk": "Denmark",
    "dm": "Dominica",
    "dz": "Algeria",
    "ee": "Estonia",
    "es": "Spain",
    "fi": "Finland",
    "fm": "Federated States of Micronesia",
    "fr": "France",
    "ga": "Gabon",
    "ge": "Georgia",
    "gg": "Guernsey",
    "gl": "Greenland",
    "gm": "Gambia",
    "gr": "Greece",
    "gy": "Guyana",
    "hn": "Honduras",
    "hr": "Croatia",
    "ht": "Haiti",
    "hu": "Hungary",
    "ie": "Ireland",
    "im": "Isle of Man",
    "iq": "Iraq",
    "is": "Iceland",
    "it": "Italy",
    "je": "Jersey",
    "jo": "Jordan",
    "kg": "Kyrgyzstan",
    "ki": "Kiribati",
    "kz": "Kazakhstan",
    "la": "Laos",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "md": "Moldova",
    "me": "Montenegro",
    "mg": "Madagascar",
    "mk": "North Macedonia",
    "ml": "Mali",
    "mn": "Mongolia",
    "mu": "Mauritius",
    "mv": "Maldives",
    "mw": "Malawi",
    "ne": "Niger",
    "nl": "Netherlands",
    "no": "Norway",
    "nr": "Nauru",
    "nu": "Niue",
    "pl": "Poland",
    "pn": "Pitcairn Islands",
    "ps": "State of Palestine",
    "pt": "Portugal",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "rw": "Rwanda",
    "sc": "Seychelles",
    "se": "Sweden",
    "sh": "Saint Helena",
    "si": "Slovenia",
    "sk": "Slovakia",
    "sm": "San Marino",
    "sn": "Senegal",
    "so": "Somalia",
    "sr": "Suriname",
    "st": "São Tomé and Príncipe",
    "td": "Chad",
    "tg": "Togo",
    "tl": "Timor-Leste",
    "tm": "Turkmenistan",
    "tn": "Tunisia",
    "to": "Tonga",
    "tt": "Trinidad and Tobago",
    "vu": "Vanuatu",
    "ws": "Samoa"
}

# Please note this dictionary is based on an assumption that the TLD corresponds to the country or territory name.
# Some TLDs are reserved for specific uses and may not represent a country or territory.
