arpabet_phone_nonverbals_library = [
    ['Sniffle', 'Indicating sadness or a cold.'],
    ['Huff', 'Showing irritation or exasperation.'],
    ['Laugh', 'Expressing amusement or joy.'],
    ['Sneer', 'Conveying contempt or disdain.'],
    ['Sigh', 'Signifying relief, tiredness, or disappointment.'],
    ['Gasp', 'Indicating shock or surprise.'],
    ['Cough', 'Clearing the throat or indicating illness.'],
    ['Yawn', 'Showing tiredness or boredom.'],
    ['Giggle', 'A light, often nervous laugh.'],
    ['Grunt', 'Expressing effort or disapproval.'],
    ['Groan', 'Indicating pain, despair, or annoyance.'],
    ['Hum', 'Showing contentment or filling silence.'],
    ['Whistle', 'Expressing cheerfulness or signaling.'],
    ['Chuckle', 'A soft, suppressed laugh.'],
    ['Sob', 'Indicating deep sorrow or crying.'],
    ['Moan', 'Suggesting pain or pleasure.'],
    ['Murmur', 'A soft, indistinct sound.'],
    ['Stammer', 'Showing hesitation or nervousness in speech.'],
    ['Shriek', 'Indicating terror or excitement.'],
    ['Whimper', 'A soft cry indicating fear or sadness.'],
    ['Chortle', 'A joyful, chuckling laugh.'],
    ['Squeal', 'High-pitched sound of excitement or fear.'],
    ['Screech', 'Harsh, high-pitched scream.'],
    ['Cluck', 'Expressing disapproval or [tsk-tsk] sound.'],
    ['Mutter', 'Speaking in a low, barely audible manner.'],
    ['Bellow', 'Loud, powerful shout.'],
    ['Roar', 'Deep, loud sound of anger or laughter.'],
    ['Pant', 'Indicating exertion or excitement.'],
    ['Snarl', 'Showing anger or hostility.'],
    ['Rasp', 'Harsh, grating sound.'],
    ['Guffaw', 'A loud, boisterous laugh.'],
    ['Snicker', 'A suppressed or half-contained laugh.'],
    ['Wail', 'A prolonged high-pitched cry of distress.'],
    ['Titter', 'A nervous, restrained laugh.'],
    ['Purr', 'Indicating contentment or pleasure.'],
    ['Whine', 'A complaining or pitiful tone.'],
    ['Whoop', 'A loud cry of excitement or joy.'],
    ['Splutter', 'Confused or excited speech.'],
    ['Hiccup', 'Involuntary sound from diaphragm spasms.'],
    ['Burp', 'Releasing air from the stomach through the mouth.'],
    ['Slurp', 'Loud sucking noise while drinking or eating.'],
    ['Chew', 'Sound of food being masticated.'],
    ['Gurgle', 'Bubbling sound, often from the throat.'],
    ['Crunch', 'Sound of hard food being bitten.'],
    ['Swallow', 'Audible gulping sound.'],
    ['Snort', 'A sound of contempt or derision.'],
    ['Mumble', 'Speaking softly and indistinctly.'],
    ['Cackle', 'A loud, raucous laugh.'],
    ['Babble', 'Incoherent or rapid talking.'],
    ['Yelp', 'A short, sharp cry of pain or alarm.'],
    ['Squeak', 'A short, high-pitched sound or voice.'],
    ['Bark', 'Sharp, loud call (not only for dogs).'],
    ['Croak', 'A rough, harsh voice or sound.'],
    ['Bawl', 'To cry loudly, often in distress.'],
    ['Growl', 'A low guttural sound of hostility.'],
    ['Breathe Heavily', 'Indicating exertion or stress.'],
    ['Shout', 'To yell or call loudly.'],
    ['Cry', 'Emotional shedding of tears.'],
    ['Exclaim', 'Speaking suddenly and emphatically.'],
    ['Whisper', 'Soft, hushed speaking.'],
    ['Rattle', 'A rapid succession of short sounds.'],
    ['ClearThroat', 'Signaling readiness to speak or discomfort.'],
    ['Sneeze', 'An involuntary expulsion of air from the nose.'],
    ['Sniff', 'Drawing air audibly up the nose.'],
    ['Spit', 'Expelling saliva forcefully from the mouth.'],
    ['Snore', 'A loud breathing sound during sleep.'],
    ['Sputter', 'Making spitting or exploding noises.'],
    ['Wheeze', 'A breathy, whistling sound from the lungs.'],
    ['Howl', 'A prolonged, mournful cry.'],
    ['Grovel', 'Indicating obsequiousness or humility.'],
    ['Squawk', 'A loud, harsh, screeching sound.'],
    ['Chirp', 'A short, sharp sound.'],
    ['Warble', 'A melodious, trilling sound.'],
    ['Trill', 'A quavering or vibratory sound.'],
    ['Peal', 'A loud, ringing sound (like laughter).'],
    ['Chime', 'A musical, ringing sound.'],
    ['Drone', 'A continuous low humming sound.'],
    ['Buzz', 'A humming or murmuring sound.'],
    ['Chime in', 'To join or interrupt a conversation.'],
    ['Bruxism', 'Clenching of the teeth.'],
    ['Gnash', 'Grinding the teeth together.'],
    ['Raspberries', 'A sound made by blowing air through relaxed but constricted lips.'],
    ['Rustle', 'A soft, whispering sound, such as that caused by the hand brushing against a groom or beard.'],
    ['Click', 'A short, sharp sound.'],
    ['Tick', 'A light, repetitive sound.'],
    ['Blare', 'A loud, harsh sound.'],
    ['Honk', 'A loud, trumpet-like sound.'],
    ['Smack', 'A loud kissing or hitting sound.'],
    ['Bang', 'A loud, abrupt sound.'],
    ['Slap', 'A sharp striking sound.'],
    ['Pop', 'A sudden, sharp sound made by plucking the thumb against the inner cheek. '],
    ['Fizz', 'A soft, sizzling sound.'],
    ['Thump', 'A heavy, dull sound.'],
    ['Clap', 'A sharp slapping sound, often of hands.'],
    ['Stamp', 'A heavy, thudding sound.'],
    ['Clink', 'A light, sharp ringing sound against a gold metal tooth or set of braces or retainer.'],
    ['Slam', 'A loud, forceful sound.'],
    ['Crack', 'A sharp, snapping sound such as with tooth enamel.'],
    ['Tinkle', 'A light, clear dripping sound such as fluid landing on the skin.'],
    ['Toot', 'A supportive short groan, resembling the sound from a horn.'],
    ['Beep', 'A short, high-pitched Shriek, resembling the short sound from a horn.'],
    ['SkepticalSighOrHum', 'A continuous Hum.']
]
